server:
  servlet:
    application-display-name: rocket-MQ
  port: 8083
spring:
  application:

    name: springboot-rocketMq


rocketmq:
  topic: my-1
  consumer:
    group_a: 'consumer_a'
    group_b: 'consumer_b'
  tags_a: 'A'
  tags_b: 'B'
  name-server: '192.168.0.23:9876'

